name: onrecord CI/CD

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create settings.py
        run: |
          mkdir -p config
          cat << EOF > config/settings.py
          import os
          import environ
          from pathlib import Path

          BASE_DIR = Path(__file__).resolve().parent.parent

          env = environ.Env()
          environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

          SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "your-default-secret-key")
          DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"
          ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")

          if "test" in os.getenv("GITHUB_ACTIONS", ""):
              DATABASES = {
                  "default": {
                      "ENGINE": "django.db.backends.sqlite3",
                      "NAME": ":memory:",
                  }
              }
          else:
              DATABASES = {
                  "default": {
                      "ENGINE": env("DB_ENGINE", default="django.db.backends.postgresql"),
                      "NAME": env("DB_NAME"),
                      "USER": env("DB_USER"),
                      "PASSWORD": env("DB_PASSWORD"),
                      "HOST": env("DB_HOST"),
                      "PORT": env.int("DB_PORT", default=5432),
                  }
              }

          INSTALLED_APPS = [
              "django.contrib.admin",
              "django.contrib.auth",
              "django.contrib.contenttypes",
              "django.contrib.sessions",
              "django.contrib.messages",
              "django.contrib.staticfiles",
              "users",
              "diaries",
              "replies",
              "communities",
              "django.contrib.sites",
              "allauth",
              "allauth.account",
              "allauth.socialaccount",
              "allauth.socialaccount.providers.naver",
              "allauth.socialaccount.providers.kakao",
              "allauth.socialaccount.providers.google",
          ]

          STATIC_URL = "/static/"
          STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
          STATICFILES_DIRS = [BASE_DIR / "static"]
          EOF

      - name: Run tests
        run: python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          ssh -o StrictHostKeyChecking=no -i deploy_key $SERVER_USER@$SERVER_HOST << 'EOF'
            set -e
            echo "배포 start❗"

            cd /root/On-Record
            git pull origin main
            echo "CI 완료❗"

            source venv/bin/activate
            pip install -r requirements.txt
            echo "패키지 업데이트 완료❗"

            python manage.py migrate
            echo "DB 마이그레이션 완료❗"

            rm -rf staticfiles/
            python manage.py collectstatic --noinput
            echo "정적 파일 생성 완료❗"

            sudo chmod -R 755 /root/On-Record/staticfiles/
            echo "정적 파일 권한 설정 완료❗"

            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            echo "Gunicorn & Nginx 재시작 완료❗"

            echo "CD 완료❗"
          EOF
