name: onrecord CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test
  deploy:
    needs: test  # 테스트 성공 시에만 배포 실행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          ssh -o StrictHostKeyChecking=no -i deploy_key $SERVER_USER@$SERVER_HOST << 'EOF'
            set -e
            echo "배포 start❗"

            # 프로젝트 디렉토리 이동
            cd /root/On-Record

            # 최신 코드 가져오기
            git pull origin main
            echo "CI 완료❗"

            # 가상환경 활성화 및 패키지 업데이트
            source venv/bin/activate
            pip install -r requirements.txt
            echo "패키지 업데이트 완료❗"

            # DB 마이그레이션
            python manage.py migrate
            echo "DB 마이그레이션 완료❗"

            # 정적 파일 수집
            rm -rf staticfiles/
            python manage.py collectstatic --noinput
            echo "정적 파일 생성 완료❗"

            # 정적 파일 권한 변경
            sudo chmod -R 755 /root/On-Record/staticfiles/
            echo "정적 파일 권한 설정 완료❗"

            # Gunicorn & Nginx 재시작
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            echo "Gunicorn & Nginx 재시작 완료❗"

            echo "CD 완료❗"
          EOF
